import { TextInput } from '@/components/form/text-input'
import { RiMailLine } from '@remixicon/react'
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "Text input component",
  description: "Generated by create next app",
};

export default function TextInputPage() {
  return (
    <div className='max-w-[340px] mx-auto pt-[112px] flex flex-col gap-6'>
      <TextInput
        label='Email'
        name='email'
        type='email'
        value={"user@gmail.com"}
        placeholder='abc@gmail.com'
        hintText='This is a hint text.'
        helpIcon
        leadingIcon={<RiMailLine />}
      />
      <TextInput
        label='Email'
        name='email-0'
        placeholder='abc@gmail.com'
        hintText='This is a hint text.'
        // error={'This is an error message.'}
        helpIcon
        leadingIcon={<RiMailLine />}
      />
      <TextInput
        label='Email'
        name='email-1'
        placeholder='abc@gmail.com'
        hintText='This is a hint text.'
        helpIcon
        disabled
      />
      <TextInput
        label='Email'
        name='email-1'
        value={"IIOO"}
        placeholder='abc@gmail.com'
        // hintText='This is a hint text.'
        helpIcon
        error='This is an error message.'
      />
      {/* <TextInput
        label='Password'
        name='password'
        type='password'
        // placeholder=''
        error={<>
          Password must be at least 8 characters long, contain at least one uppercase letter, one lowercase letter, one number, and one special character.
        </>}
      // helpIcon
      // error='This is an error message.'
      /> */}
    </div>
  )
}
