import { NavBar } from '@/components/navigation/nav-bar'
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "Navbar component | GFE - Design System",
  description: "Generated by create next app",
};

export default function NavbarPage() {
  return (
    <>
      <NavBar />
    </>
  )
}
