import type { Metadata } from "next";
import "./globals.css";
import { notoSans } from "@/config";




export const metadata: Metadata = {
  title: {
    template: "%s | GFE - Design System",
    default: "GFE - Design System",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
