name: Deploy Storybook to Vercel

on:
  push:
    branches:
      - main # hoặc branch chính bạn dùng

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Lấy code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Cài Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Cài dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build Storybook
      - name: Build Storybook
        run: npm run build-storybook

      # 5. Deploy ra branch "storybook-deploy"
      - name: Deploy Storybook to storybook-deploy branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          publish_branch: storybook-deploy
          force_orphan: true
